version: '3'

services:
    web-scrapy:
        image: 'web-scrapy'
        container_name: 'web-scrapy'
        build:
            context: .
            dockerfile: Dockerfile-web
        restart: unless-stopped
        volumes:
            - ./app/workdir:/workdir
        networks:
            - local
        command: "tail -f /dev/null"
    
    mongo-scrapy:
        image: mongo:latest
        container_name: 'mongo-scrapy'
        volumes:
            - ./app/db:/data/db
            - ./mongo-config:/home
        networks:
            - local
        expose:
            - "27017"
        ports:
            - "686:27017" 
        command: 'mongod'
    
networks:
    local:
        driver: bridge
